# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cp surge4.conf surge4.conf.temp
          sed -i 's|YOUR_SUB_URL1|${{ secrets.SUB_URL1 }}|' surge4.conf.temp
          sed -i 's|YOUR_SUB_URL2|${{ secrets.SUB_URL2 }}|' surge4.conf.temp
          sed -i 's|YOUR_SUB_URL3|${{ secrets.SUB_URL3 }}|' surge4.conf.temp
          sed -i 's|YOUR_SUB_URL4|${{ secrets.SUB_URL4 }}|' surge4.conf.temp
          sed -i 's|YOUR_SUB_URL5|${{ secrets.SUB_URL5 }}|' surge4.conf.temp
          cat surge4.conf.temp
          rm -f surge4.conf.temp
